In [2]:
import torch

In [13]:
import numpy as np

In [4]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [5]:
# create a random tensor
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[9.2755e-39, 1.0561e-38, 1.1204e-38],
        [1.0010e-38, 1.0102e-38, 6.2449e-39]])


In [7]:
describe(torch.rand(2, 3)) # uniform random
print("")
describe(torch.randn(2, 3)) # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9011, 0.8704, 0.2509],
        [0.9088, 0.3124, 0.6425]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4591,  1.9310,  0.2290],
        [ 1.5749, -0.3343,  0.3033]])


In [10]:
describe(torch.zeros(2, 3)) # creating a tensor of zeros
x = torch.ones(2, 3) # creating a tensor of ones
describe(x)
# underscore does an in-place operation which means the variable is changed without creating a new object.
# the below function fills the variable x with 5s
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [12]:
x = torch.Tensor([[1, 2, 3, 4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([1, 6])
Values: 
tensor([[1., 2., 3., 4., 5., 6.]])


In [15]:
# convert a numpy array to a tensor
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.8725, 0.2752, 0.2466],
        [0.5397, 0.9763, 0.6883]], dtype=torch.float64)


In [18]:
x = torch.FloatTensor([[1,2,3,4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([1, 6])
Values: 
tensor([[1., 2., 3., 4., 5., 6.]])


In [20]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([1, 6])
Values: 
tensor([[1, 2, 3, 4, 5, 6]])


In [23]:
x = torch.randn(2, 3)
describe(x)

# adding 2 tensors
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.9295,  0.3987, -0.4933],
        [ 1.5645, -0.0079, -0.8838]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.8589,  0.7975, -0.9865],
        [ 3.1289, -0.0158, -1.7675]])


In [32]:
# creates a 1D array from 0 to n-1 with size n
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [33]:
# conver the above 1D arrray into a 2D one
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [34]:
# add all the columns of the above 2D array
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [35]:
# add all the rows of the above 2D array
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [37]:
print(torch.cuda.is_available())

True


In [39]:
# preferred method: device agnostic tensor instantiation
# this line allows for the use of GPU if available.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [40]:
print(device)

cuda


In [42]:
x = torch.rand(3, 3).to(device)
describe(x)

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.3814, 0.3166, 0.5520],
        [0.3574, 0.1214, 0.6802],
        [0.2634, 0.0351, 0.7747]], device='cuda:0')


In [45]:
y = torch.rand(3, 3)
x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [49]:
# make sure all tensors are on the same device
cpu_device = torch.device("cpu")
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[0.5151, 0.9216, 1.4965],
        [0.6371, 0.3993, 0.7064],
        [0.6258, 0.3336, 1.1413]])